 # @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  #- 7

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  #fast_finish: true

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin:$HOME/.phpenv/bin"

before_install:
  - composer self-update
  # Codesniffer and Coder

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  # Install Drush
  - composer global require drush/drush
  - mysql -e 'create database drupal;'
  - composer install
    # Install drupal default profile
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - drush en simpletest -y

script:
  - php core/scripts/run-tests.sh --color --verbose --concurrency 4 --all --php /home/travis/.phpenv/shims/php  --url http://127.0.0.1:8080

